config/routes.rb
Rails.application.routes.draw do

  namespace :public do
    get 'searchs/search'
  end
  get 'searchs/search'
  #namespace内ではエラーが出たため外に記述
  devise_for :customers, skip: 'registrations', controllers: {
      sessions:      'customers/sessions',
      passwords:     'customers/passwords',
      registrations: 'customers/registrations',
    }
  #editのURLが重複するのを避けるため、registrationsだけ個別に設定
  devise_scope :customer do
      get '/customers/sign_up' => 'customers/registrations#new',    as: :new_customer_registration
      post '/customers'        => 'customers/registrations#create', as: :customer_registration
  end

  devise_for :admin, path: "/admin", controllers: {
      sessions:      'admins/sessions',
      passwords:     'admins/passwords',
      registrations: 'admins/registrations'
    }

  namespace :admin do
    root to:'homes#top'
    resources :customers,      only: [:index, :show, :edit, :update]
    resources :products,       except: [:destroy] do
      resources :comments,     only:[:destroy]
    end
    resources :genres,         only: [:index, :edit, :create, :update]
    get '/order_infos/sales_status' => 'order_infos#status_search'
    resources :order_infos,    only: [:index, :show, :update] do
     resources :order_products, only: [:update]
    end
  end

  namespace :public, path:"" do
    #homes
    root to:'homes#top'
    get '/about' => 'homes#about'

    #customers
    get '/customers'             => 'customers#show'
    get '/customers/edit'        => 'customers#edit'
    patch '/customers'           => 'customers#update'
    get '/customers/suspend'     => 'customers#suspend'
    patch '/customers/suspended' => 'customers#suspended'

    resources :addresses,     except:[:show, :new]
    resources :products,      only:[:index, :show] do
      resources :comments,    only:[:create, :destroy]
    end
    resources :cart_products, only:[:index, :create, :update, :destroy]

    #cart_producst
    get '/cart_products/delete_all' => 'cart_products#delete_all'

    #order_infos
    get '/order_infos/confirm'         => 'order_infos#confirm'
    get '/order_infos/complete'        => 'order_infos#complete'
    resources :order_infos,  only:[:index, :show, :new, :create]

    #searchs
    get '/search' => 'searchs#search'

  end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :email,             presence: true
  validates :family_name,       presence: true
  validates :given_name,        presence: true
  validates :family_name_kana,  presence: true
  validates :given_name_kana,   presence: true
  validates :phone,             presence: true
  validates :postal_code,       presence: true
  validates :address,           presence: true


  has_many :cart_products, dependent: :destroy
  has_many :order_infos,   dependent: :destroy
  has_many :addresses,     dependent: :destroy
  has_many :comments,      dependent: :destroy


end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < Admin::Base
  def index
    @customers = Customer.all.page(params[:page]).per(10)
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      flash[:notice] = "会員情報を更新しました"
      redirect_to admin_customers_path
    else
      render :edit
    end
  end

  private
  def customer_params
    params.require(:customer).permit(:email, :family_name, :given_name, :family_name_kana, 
                                    :given_name_kana, :phone, :address, :postal_code, :suspended)
  end
end

app/controllers/customers/confirmations_controller.rb
# frozen_string_literal: true

class Customers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/customers/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Customers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/customers/passwords_controller.rb
# frozen_string_literal: true

class Customers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/customers/registrations_controller.rb
# frozen_string_literal: true

class Customers::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/customers/sessions_controller.rb
# frozen_string_literal: true

class Customers::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
  before_action :reject_inactive_customer, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  protected

  def reject_inactive_customer
    @customer = Customer.find_by(email: params["customer"]["email"])
    if @customer
      if @customer.suspended
        flash[:notice] = "退会済みのためログインできません"
        redirect_to new_customer_session_path
      end
    end
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/customers/unlocks_controller.rb
# frozen_string_literal: true

class Customers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/edit.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <%= render 'layouts/error', model:@customer %>
  </div>
  <div class="row">
    <div class="col">
      <h2 class="m-5 bg-light"><%= @customer.family_name + @customer.given_name %>さんの会員情報編集</h2>
      <%=form_with model:@customer, url:admin_customer_path(@customer), local:true do |f| %>
        <div class="customer-id" data-score="<%= @customer.id %>">
          <label for="customer-id" class="w-25">会員ID</label>
          <%= @customer.id %>
        </div>
        <div class="form-group">
          <label for="customer-name" class="w-25">氏名</label>
          <%= f.text_field :family_name,      class:"customer-family_name" %>
          <%= f.text_field :given_name,       class:"customer-given_name" %>
        </div>
        <div class="form-group">
          <label for="customer-name-kana" class="w-25">フリガナ</label>
          <%= f.text_field :family_name_kana, class:"customer-family-name-kana" %>
          <%= f.text_field :given_name_kana,  class:"customer-given-name-kana" %>
        </div>
        <div class="form-group">
          <label for="postal-code" class="w-25">郵便番号</label>
          <%= f.text_field :postal_code,       class:"postal-code" %>
        </div>
        <div class="form-group">
          <label for="address" class="w-25">住所</label>
          <%= f.text_field :address,           class:"address",size:50 %>
        </div>
        <div class="form-group">
          <label for="phone" class="w-25">電話番号</label>
          <%= f.text_field :phone,             class:"phone" %>
        </div>
        <div class="form-group">
          <label for="email" class="w-25">メールアドレス</label>
          <%= f.text_field :email,             class:"email" %>
        </div>
        <div class="form-group">
          <label for="status" class="w-25">会員ステータス</label>
          <%= f.radio_button :suspended, false %>有効　<%= f.radio_button :suspended, true %>退会
        </div>
        <div class="form-group">
          <%= f.submit '変更を保存',class:"btn btn-success pl-30" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/customers/index.html.erb
<div class="row">
  <h2 class="bg-light m-3">会員一覧</h2>
</div>

<div class="row">
  <div class="col-md-12">
    <%= paginate @customers %>
    <table class="table table-hover table-inverse">
      <thead class="bg-light">
        <tr>
          <th>会員ID</th>
          <th>氏名</th>
          <th>メールアドレス</th>
          <th>ステータス</th>
        </tr>
      </thead>
      <tbody>
        <% @customers.each do |c| %>
        <tr>
          <td><%= c.id %></td>
          <td><%= link_to (c.family_name + c.given_name), admin_customer_path(c) %></td>
          <td><%= c.email %></td>
          <% if c.suspended %>
            <td class="text-secondary">退会</td>
          <% else %>
            <td class="text-success">有効</td>
          <% end %>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/admin/customers/show.html.erb
<div class="row">
  <h2 class="m-5 bg-light">
    <%= @customer.family_name + @customer.given_name %>さんの会員詳細
  </h2>
</div>

<div class="row">
  <div class="col-md-9">
    <div class="customer-id">
      <label for="customer-id" class="w-25">会員ID</label>
      <%= @customer.id %>
    </div>
    <div class="form-group">
      <label for="customer-name" class="w-25">氏名</label>
      <%= @customer.family_name + @customer.given_name %>
    </div>
    <div class="form-group">
      <label for="customer-name-kana" class="w-25">フリガナ</label>
      <%= @customer.family_name_kana + @customer.given_name_kana %>
    </div>
    <div class="form-group">
      <label for="postal-code" class="w-25">郵便番号</label>
      <%= @customer.postal_code %>
    </div>
    <div class="form-group">
      <label for="address" class="w-25">住所</label>
      <%= @customer.address %>
    </div>
    <div class="form-group">
      <label for="phone" class="w-25">電話番号</label>
      <%= @customer.phone %>
    </div>
    <div class="form-group">
      <label for="phone" class="w-25">メールアドレス</label>
      <%= @customer.email %>
    </div>
    <div class="form-group">
      <label for="phone" class="w-25">会員ステータス</label>
      <% if @customer.suspended %>
        <span class="text-secondary">退会</span></p>
      <% else %>
        <span class="text-success">有効</span></p>
      <% end %>
    </div>
    <div class="m-10">
      <%= link_to "編集する",edit_admin_customer_path(@customer), {class: "btn btn-success"} %>
      <%= link_to "注文履歴一覧を見る", admin_order_infos_path,{class: "btn btn-primary ml-5"} %>
    </div>
  </div>
</div>