config/routes.rb
Rails.application.routes.draw do

  namespace :public do
    get 'searchs/search'
  end
  get 'searchs/search'
  #namespace内ではエラーが出たため外に記述
  devise_for :customers, skip: 'registrations', controllers: {
      sessions:      'customers/sessions',
      passwords:     'customers/passwords',
      registrations: 'customers/registrations',
    }
  #editのURLが重複するのを避けるため、registrationsだけ個別に設定
  devise_scope :customer do
      get '/customers/sign_up' => 'customers/registrations#new',    as: :new_customer_registration
      post '/customers'        => 'customers/registrations#create', as: :customer_registration
  end

  devise_for :admin, path: "/admin", controllers: {
      sessions:      'admins/sessions',
      passwords:     'admins/passwords',
      registrations: 'admins/registrations'
    }

  namespace :admin do
    root to:'homes#top'
    resources :customers,      only: [:index, :show, :edit, :update]
    resources :products,       except: [:destroy] do
      resources :comments,     only:[:destroy]
    end
    resources :genres,         only: [:index, :edit, :create, :update]
    get '/order_infos/sales_status' => 'order_infos#status_search'
    resources :order_infos,    only: [:index, :show, :update] do
     resources :order_products, only: [:update]
    end
  end

  namespace :public, path:"" do
    #homes
    root to:'homes#top'
    get '/about' => 'homes#about'

    #customers
    get '/customers'             => 'customers#show'
    get '/customers/edit'        => 'customers#edit'
    patch '/customers'           => 'customers#update'
    get '/customers/suspend'     => 'customers#suspend'
    patch '/customers/suspended' => 'customers#suspended'

    resources :addresses,     except:[:show, :new]
    resources :products,      only:[:index, :show] do
      resources :comments,    only:[:create, :destroy]
    end
    resources :cart_products, only:[:index, :create, :update, :destroy]

    #cart_producst
    get '/cart_products/delete_all' => 'cart_products#delete_all'

    #order_infos
    get '/order_infos/confirm'         => 'order_infos#confirm'
    get '/order_infos/complete'        => 'order_infos#complete'
    resources :order_infos,  only:[:index, :show, :new, :create]

    #searchs
    get '/search' => 'searchs#search'

  end

end

app/models/order_info.rb
class OrderInfo < ApplicationRecord
  validates :customer_id, :postage, :total_payment, :payment_method,
            :order_status, :postal_code, :address, :name,
            presence: true


  def full_name(family_name, given_name)
    "#{family_name} #{given_name}"
  end

  def self.destination(postal_code, address, name)
    "〒#{postal_code} #{address} #{name}"
  end

  def self.status_search(sortword)
    case sortword
    when 0
      where(order_status: 0)
    when 1
      where(order_status: 1)
    when 2
      where(order_status: 2)
    when 3
      where(order_status: 3)
    when 4
      where(order_status: 4)
    end
  end

  belongs_to :customer
  has_many :order_products, class_name: "OrderProduct", foreign_key: "order_id", dependent: :destroy

  scope :scope_six_days_ago, ->   {where(created_at: Time.current.ago(6.days).all_day)}
  scope :scope_five_days_ago, ->  {where(created_at: Time.current.ago(5.days).all_day)}
  scope :scope_four_days_ago, ->  {where(created_at: Time.current.ago(4.days).all_day)}
  scope :scope_three_days_ago, -> {where(created_at: Time.current.ago(3.days).all_day)}
  scope :scope_two_days_ago, ->   {where(created_at: Time.current.ago(2.days).all_day)}
  scope :scope_a_day_ago, ->      {where(created_at: Time.current.ago(1.days).all_day)}
  scope :scope_today, ->          {where(created_at: Time.current.beginning_of_day..Time.current)}
end

app/controllers/admin/order_infos_controller.rb
class Admin::OrderInfosController < Admin::Base
  def index
    @order_infos = OrderInfo.all.page(params[:page]).per(10)

    sales_today =          OrderInfo.scope_today.sum(:total_payment)
    sales_a_day_ago =      OrderInfo.scope_a_day_ago.sum(:total_payment)
    sales_two_days_ago =   OrderInfo.scope_two_days_ago.sum(:total_payment)
    sales_three_days_ago = OrderInfo.scope_three_days_ago.sum(:total_payment)
    sales_four_days_ago =  OrderInfo.scope_four_days_ago.sum(:total_payment)
    sales_five_days_ago =  OrderInfo.scope_five_days_ago.sum(:total_payment)
    sales_six_days_ago =   OrderInfo.scope_six_days_ago.sum(:total_payment)
    @sales_array = [sales_six_days_ago, sales_five_days_ago, sales_four_days_ago, sales_three_days_ago, sales_two_days_ago, sales_a_day_ago, sales_today]

  end

  def status_search
    @searchword = params[:sortword]
    @order_infos = OrderInfo.status_search(@searchword.to_i).page(params[:page]).per(10)
  end

  def show
    @order_info = OrderInfo.find(params[:id])
  end

  def update
    @order_info = OrderInfo.find(params[:id])
    if @order_info.update(order_info_params)
      if @order_info.order_status == 1 #入金確認
        @order_info.order_products.each do |product|
          product.update(product_status: 1) #制作待ち
        end
      end
      redirect_to admin_order_info_path(@order_info)
    else
      render :show
    end
  end

  private
  def order_info_params
    params.require(:order_info).permit(:order_status)
  end
end

app/helpers/admin/order_infos_helper.rb
module Admin::OrderInfosHelper
  def order_status_hash
    order_hash = { '0': "入金待ち", '1': "入金確認", '2':"製作中", '3':"発送準備中", '4':"発送済み" }
    return order_hash
  end

  def sales_status_hash
    sales_hash = { '0': "着手不可", '1': "製作待ち", '2':"製作中", '3':"制作完了" }
    return sales_hash
  end

  def payment_method_hash
    payment_hash = { '0': "クレジットカード", '1': "銀行振込" }
    return payment_hash
  end
end

app/views/admin/order_infos/index.html.erb
<div class="row">
  <h2 class="bg-light">直近一週間の売上推移</h2>
</div>
<div class="row">
  <div class="col-md-12">
    <canvas id="myChart" width="400" height="150"></canvas>
    <script>
    var ctx = document.getElementById('myChart').getContext('2d');
    var myChart = new Chart(ctx, {
        type: 'line',
        data: {
            labels: ['6日前', '5日前', '4日前', '3日前', '2日前', '前日', '当日'],
            datasets: [{
                label: '売上高(円)',
                data: <%= @sales_array %> ,
                borderWidth: 2,
                backgroundColor:['rgba(100, 159, 64, 0.0)'],
                borderColor: 'blue',
            }]
        },
        options: {
            scales: {
                y: {
                    beginAtZero: true
                }
            }
        }
    });
    </script>
  </div>
</div>

<div class="row">
  <h2 class="mt-5 mb-3 bg-light">
    注文履歴一覧
  </h2>
</div>

<div class="row">
  <div class="col-md-12">
    <div class="row pb-2">
      <dib class="offset-md-9">
        <%= form_with model: @order_infos, url: admin_order_infos_sales_status_path, method: :get, local: true do |f| %>
          <%= f.select :sortword, [['入金待ち', 0], ['入金確認', 1], ['制作中', 2], ['発送準備中', 3], ['発送済み', 4]] %>
          <%= f.submit 'ステータスで絞る' %>
        <% end %>
      </dib>
    </div>

    <%= paginate @order_infos %>
    <table class="table table-hover table-inverse">
      <thead class="bg-light">
        <tr>
          <th>購入日時</th>
          <th>購入者</th>
          <th>注文個数</th>
          <th>注文ステータス</th>
        </tr>
      </thead>
      <tbody>
        <% @order_infos.each do |order| %>
        <tr>
          <td><%= link_to order.created_at.strftime("%Y/%m/%d %H:%M"), admin_order_info_path(order) %></td>
          <td><%=  (order.customer.family_name + order.customer.given_name) %></td>
          <td><%= order.order_products.sum(:quantity) %></td>
          <td><%= order_status_hash[:"#{order.order_status}"] %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/admin/order_infos/show.html.erb
<div class="row">
  <h2 class="m-5 bg-light">注文履歴詳細</h2>
</div>

<div class="row order-detail">
    <div class="col-md-12">
      <div>
        <label for="customer-name" class="w-25">購入者</label>
        <%= @order_info.customer.family_name + " " + @order_info.customer.given_name %>
      </div>
      <div class="form-group">
        <label for="order-date" class="w-25">注文日</label>
        <%= @order_info.created_at.strftime("%Y/%m/%d %H:%M:%S") %>
      </div>
      <div class="form-group">
        <label for="order-address" class="w-25">配送先</label>
        〒<%= @order_info.postal_code%>  <%= @order_info.address %></br>
        <%= @order_info.name %>
      </div>
      <div class="form-group">
        <label for="payment-method" class="w-25">支払方法</label>
        <%= payment_method_hash[:"#{@order_info.payment_method}"] %>
      </div>
      <%= form_with model:@order_info, url:admin_order_info_path(@order_info), local:true do |f| %>
      <div class="form-group">
        <label for="order-status" class="w-25">注文ステータス</label>
        <%= f.select :order_status, [["入金待ち", 0], ["入金確認", 1], ["製作中", 2],
                                     ["発送準備中", 3], ["発送済み", 4]] %>
        <%= f.submit '注文の更新',class:"btn btn-success ml-3" %>
      </div>
      <% end %>
    </div>
  </div>

  <div class="row order-products-detail">
    <div class="col-md-10">
      <table class="table table-hover table-inverse">
      <thead class="bg-light">
        <tr>
          <th>商品名</th>
          <th>単価（税込）</th>
          <th>数量</th>
          <th>小計</th>
          <th>製作ステータス</th>
        </tr>
      </thead>
      <tbody>
        <% @order_info.order_products.each do |product| %>
        <tr class="order-product">
          <td><%=  product.product.name %></td>
          <td><%=  product.price %></td>
          <td><%= product.quantity %></td>
          <td><%=  product.price * product.quantity %></td>
          <td>
          <%= form_with(model:[@order_info, product], url: admin_order_info_order_product_path(@order_info, product), method: :patch, local:true) do |f| %>
            <%= f.select :product_status, [["着手不可", 0], ["制作待ち", 1], ["製作中", 2], ["製作完了", 3]]  %>
            <%= f.submit "製品の更新", class:"btn btn-success ml-3" %>
          <% end %>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
    </div>

    <div class="col-md-2">
      <table>
        <tr>
          <th>商品合計</th>
          <td class="text-right">
            <% product_sum = 0 %>
            <% @order_info.order_products.each do |product| %>
              <% product_sum += product.price * product.quantity %>
            <% end %>
            <%= product_sum.to_s(:delimited) %>円
          </td>
        </tr>
        <tr><th>送料</th><td class="text-right"><%= @order_info.postage.to_s(:delimited) %>円</td></tr>
        <tt><th>請求金額合計</th><td class="text-right"><%= @order_info.total_payment.to_s(:delimited) %>円</td></tr>
      </table>
    </div>
  </div>

  <div class="row">
    <%= link_to "一覧に戻る", admin_order_infos_path, class:"btn btn-info btn-sm offset-9" %>
  </div>

app/views/admin/order_infos/status_search.html.erb
<% status = { '0': "入金待ち", '1': "入金確認", '2':"製作中", '3':"発送準備中", '4':"発送済み" } %>


<div class="row">
  <div class="col-md-12">
    <h2 class="m-3 bg-light">
      注文履歴一覧　”<%= status[:"#{@searchword}"] %>”
    </h2>

    <%= paginate @order_infos %>
    <table class="table table-hover table-inverse">
      <thead class="bg-light">
        <tr>
          <th>購入日時</th>
          <th>購入者</th>
          <th>注文個数</th>
          <th>注文ステータス</th>
        </tr>
      </thead>
      <tbody>
        <% @order_infos.each do |order| %>
        <tr>
          <td><%= link_to order.created_at.strftime("%Y/%m/%d %H:%M:%S"), admin_order_info_path(order) %></td>
          <td><%=  (order.customer.family_name + order.customer.given_name) %></td>
          <td><%= order.order_products.sum(:quantity) %></td>
          <td>
            <%= status[:"#{order.order_status.to_s}" ] %><br>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>
<div class="row">
    <%= link_to "一覧に戻る", admin_order_infos_path, class:"btn btn-info btn-sm offset-10" %>
</div>