config/routes.rb
Rails.application.routes.draw do

  namespace :public do
    get 'searchs/search'
  end
  get 'searchs/search'
  #namespace内ではエラーが出たため外に記述
  devise_for :customers, skip: 'registrations', controllers: {
      sessions:      'customers/sessions',
      passwords:     'customers/passwords',
      registrations: 'customers/registrations',
    }
  #editのURLが重複するのを避けるため、registrationsだけ個別に設定
  devise_scope :customer do
      get '/customers/sign_up' => 'customers/registrations#new',    as: :new_customer_registration
      post '/customers'        => 'customers/registrations#create', as: :customer_registration
  end

  devise_for :admin, path: "/admin", controllers: {
      sessions:      'admins/sessions',
      passwords:     'admins/passwords',
      registrations: 'admins/registrations'
    }

  namespace :admin do
    root to:'homes#top'
    resources :customers,      only: [:index, :show, :edit, :update]
    resources :products,       except: [:destroy] do
      resources :comments,     only:[:destroy]
    end
    resources :genres,         only: [:index, :edit, :create, :update]
    get '/order_infos/sales_status' => 'order_infos#status_search'
    resources :order_infos,    only: [:index, :show, :update] do
     resources :order_products, only: [:update]
    end
  end

  namespace :public, path:"" do
    #homes
    root to:'homes#top'
    get '/about' => 'homes#about'

    #customers
    get '/customers'             => 'customers#show'
    get '/customers/edit'        => 'customers#edit'
    patch '/customers'           => 'customers#update'
    get '/customers/suspend'     => 'customers#suspend'
    patch '/customers/suspended' => 'customers#suspended'

    resources :addresses,     except:[:show, :new]
    resources :products,      only:[:index, :show] do
      resources :comments,    only:[:create, :destroy]
    end
    resources :cart_products, only:[:index, :create, :update, :destroy]

    #cart_producst
    get '/cart_products/delete_all' => 'cart_products#delete_all'

    #order_infos
    get '/order_infos/confirm'         => 'order_infos#confirm'
    get '/order_infos/complete'        => 'order_infos#complete'
    resources :order_infos,  only:[:index, :show, :new, :create]

    #searchs
    get '/search' => 'searchs#search'

  end

end

app/models/product.rb
class Product < ApplicationRecord
  attachment :image

  validates :name, :introduction, :genre_id, :price, :image, presence: true
  has_many :cart_products, dependent: :destroy
  belongs_to :genre
  has_many :order_products, dependent: :destroy
  has_many :comments, dependent: :destroy

  TAX_RATE = 1.1

  def tax_price
    (self.price*TAX_RATE).floor
  end

  def status
    self.sales_status == true ? "販売中" : "販売停止中"
  end

end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < Admin::Base

  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
  end

  def new
    @product = Product.new
  end

  def edit
    @product = Product.find(params[:id])
  end

  def create
    @product = Product.new(product_params)

    if @product.save
      flash.notice = "商品を追加しました。"
      redirect_to admin_product_path(@product.id)
    else
      flash.now.alert = "入力に誤りがあります。"
      render action: "new"
    end

  end

  def update
    @product = Product.find(params[:id])

    if @product.update(product_params)
      flash.notice = "商品情報を更新しました。"
      redirect_to action: "index"
    else
      flash.now.alert = "入力に誤りがあります。"
      render action: "edit"
    end
  end

  private
  def product_params
    params.require(:product).permit(:name, :introduction, :genre_id, :price, :sales_status, :image)
  end

end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/views/shared/products/_form.html.erb
  <%= form_with model: product, url: path, class: "col-12", local: true do |f| %>
    <% product_form_hash.each do |key, value| %>
      <div class="form-group">
        <div class="row">
          
          <div class="col-3">
            <%= f.label key, value[:label] %>
          </div>
          
          <div class="col">
            <% if value[:form] == :field %>
              <%= f.text_field key, placeholder: value[:placeholder], size:"40x30" %><%= value[:option] %>
            <% elsif value[:form] == :area %>
              <%= f.text_area key, placeholder: value[:placeholder], size:"40x3" %>
            <% elsif value[:form] == :attachment %>
              <%= f.attachment_field key %>
            <% elsif value[:form] == :genre %>
              <%= f.collection_select key, Genre.all, :id, :name, { include_blank: "--選択してください--"}, {:style => "width:300px" } %>
            <% end %>
          </div>
          
        </div>
      </div>
    <% end %>
    
    <div class="row">
      <div class="col-3">
        <%= f.label :sales_state, "販売ステータス" %>
      </div>
      <div class="col">
        <%= f.radio_button :sales_status, true %>
        <%= f.label :sales_status, "販売中", class:"salse_true" %>
        
        <%= f.radio_button :sales_status, false %>
        <%= f.label :sales_status, "販売停止中", class:"sales_false" %>
      </div>
    </div>
    
    <%= f.submit "新規登録", class:"btn btn-primary" %>
  <% end %>

app/views/shared/products/_product_detail.html.erb
<div class="row">
  <div class="col-4">
    <%= attachment_image_tag product, :image, format: 'jpeg', size: '250x250' %>
  </div>

  <table class="table col-6">
    <tr><th>商品名</th><td><%= product.name %></td></tr>
    <tr><th>商品説明</th><td><%= product.introduction %></td></tr>
    <tr><th>ジャンル</th><td><%= product.genre.name %></td></tr>

    <% if admin_signed_in? %>
      <tr><th>税込価格（税抜き価格）</th><td><%= product.tax_price %> (<%= product.price %>) 円</td></tr>
    <% else %>
      <tr><th>価格（税込）</th><td><%= product.tax_price %> 円</td></tr>
    <% end %>

    <tr>
      <th>在庫情報</th>
        <% if product.sales_status %>
          <td class="text-success"><%= product.status %></td>
        <% else %>
          <td class="text-secondary"><%= product.status %></td>
        <% end %>
    </tr>

    <% if product.sales_status %>
      <% if customer_signed_in? %>
        <tr><th><%= render "shared/products/purchase_form", cart_product: @cart_product, product: product, path: public_cart_products_path %></th><td></td></tr>
      <% elsif !admin_signed_in? %>
        <tr><th></th><td><%= link_to "購入", new_customer_session_path, class: "btn btn-info btn-sm" %></td></tr>
      <% end %>
    <% end %>

    <% if admin_signed_in? %>
      <tr><th></th><td><%= link_to "edit", edit_admin_product_path(product.id),class: "btn btn-info btn-sm" %></td></tr>
    <% end %>

    <% if customer_signed_in? %>
      <% if have_you_ordered_product? && !have_you_already_comment? %>
        <tr>
          <th>コメントする</th>
          <td>
            <%= form_with(model:@comment, url:public_product_comments_path(product), method: :post, local:true) do |f| %>
              <%= f.text_area :body %>
              <%= f.hidden_field :product_id, value: product.id %>
              <%= f.submit "コメントする", {class:"btn btn-primary ml-3"} %>
            <% end %>
          </td>
        </tr>
      <% end %>
    <% end %>
    <tr>
      <th>コメント(<%= product.comments.count %>)</th><td></td>
    </tr>
    <% product.comments.each do |comment| %>
    <tr>
      <th></th>
        <td>
          <%= comment.body %>
          <% if admin_signed_in? %>
            <%= link_to "コメントを削除", admin_product_comment_path(product,comment,customer_id:comment.customer.id), method: :delete, class:"btn btn-danger" %>
          <% elsif signed_in? %>
            <% if comment.customer_id == current_customer.id %>
              <%= link_to "コメントを削除", public_product_comment_path(product,comment,customer_id:comment.customer.id), method: :delete, class:"btn btn-danger" %>
            <% end %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </table>
</div>

app/views/shared/products/_products_list.html.erb
<h2 class="mb-3">商品一覧(全<%= products.count %>件)</h2>
<div class="row product-index">
  <% products.each do |product| %>
    <div class="col-3">
      <!--商品画像-->
      <div class="mb-2">
        <%= link_to public_product_path(product.id) do %>
          <%= attachment_image_tag product, :image, format: 'jpeg', size: '250x200', alt:"image#{product.id}" %>
        <% end %>
      </div>
      <!--商品情報-->
      <div class="mb-2">
        <%= product.name %>
      </div>
      <div class="mb-2">
      ¥<%= product.tax_price %></br>
      </div>
    </div>
  <% end %>
</div>

app/views/shared/products/_purchase_form.html.erb
<%= form_with model: cart_product, url: path, local: true, class:"cartin" do |f| %>
    <%= f.select :quantity, [1,2,3,4,5,6,7,8,9,10] %>
    <%= f.hidden_field :customer_id, :value => current_customer.id %>
    <%= f.hidden_field :product_id, :value => product.id %>

    <% if controller_name == "products" %>
      <%= f.submit "カートに入れる" %>
    <% elsif controller_name == "cart_products" %>
      <%= f.submit "変更" %>
    <% end %>

<% end %>