config/routes.rb
Rails.application.routes.draw do

  namespace :public do
    get 'searchs/search'
  end
  get 'searchs/search'
  #namespace内ではエラーが出たため外に記述
  devise_for :customers, skip: 'registrations', controllers: {
      sessions:      'customers/sessions',
      passwords:     'customers/passwords',
      registrations: 'customers/registrations',
    }
  #editのURLが重複するのを避けるため、registrationsだけ個別に設定
  devise_scope :customer do
      get '/customers/sign_up' => 'customers/registrations#new',    as: :new_customer_registration
      post '/customers'        => 'customers/registrations#create', as: :customer_registration
  end

  devise_for :admin, path: "/admin", controllers: {
      sessions:      'admins/sessions',
      passwords:     'admins/passwords',
      registrations: 'admins/registrations'
    }

  namespace :admin do
    root to:'homes#top'
    resources :customers,      only: [:index, :show, :edit, :update]
    resources :products,       except: [:destroy] do
      resources :comments,     only:[:destroy]
    end
    resources :genres,         only: [:index, :edit, :create, :update]
    get '/order_infos/sales_status' => 'order_infos#status_search'
    resources :order_infos,    only: [:index, :show, :update] do
     resources :order_products, only: [:update]
    end
  end

  namespace :public, path:"" do
    #homes
    root to:'homes#top'
    get '/about' => 'homes#about'

    #customers
    get '/customers'             => 'customers#show'
    get '/customers/edit'        => 'customers#edit'
    patch '/customers'           => 'customers#update'
    get '/customers/suspend'     => 'customers#suspend'
    patch '/customers/suspended' => 'customers#suspended'

    resources :addresses,     except:[:show, :new]
    resources :products,      only:[:index, :show] do
      resources :comments,    only:[:create, :destroy]
    end
    resources :cart_products, only:[:index, :create, :update, :destroy]

    #cart_producst
    get '/cart_products/delete_all' => 'cart_products#delete_all'

    #order_infos
    get '/order_infos/confirm'         => 'order_infos#confirm'
    get '/order_infos/complete'        => 'order_infos#complete'
    resources :order_infos,  only:[:index, :show, :new, :create]

    #searchs
    get '/search' => 'searchs#search'

  end

end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer

  validates :address,     presence: true
  validates :name,        presence: true
  validates :postal_code, presence: true

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

end

app/models/cart_product.rb
class CartProduct < ApplicationRecord

  def subtotal
    price = Product.find(self.product_id).tax_price
    quantity = self.quantity

    return (price*quantity).to_i
  end

  belongs_to :customer
  belongs_to :product


end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :customer
  belongs_to :product

  validates :body, presence: true
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :email,             presence: true
  validates :family_name,       presence: true
  validates :given_name,        presence: true
  validates :family_name_kana,  presence: true
  validates :given_name_kana,   presence: true
  validates :phone,             presence: true
  validates :postal_code,       presence: true
  validates :address,           presence: true


  has_many :cart_products, dependent: :destroy
  has_many :order_infos,   dependent: :destroy
  has_many :addresses,     dependent: :destroy
  has_many :comments,      dependent: :destroy


end

app/models/genre.rb
class Genre < ApplicationRecord
  validates :name, presence: true
  
  
end

app/models/order_info.rb
class OrderInfo < ApplicationRecord
  validates :customer_id, :postage, :total_payment, :payment_method,
            :order_status, :postal_code, :address, :name,
            presence: true


  def full_name(family_name, given_name)
    "#{family_name} #{given_name}"
  end

  def self.destination(postal_code, address, name)
    "〒#{postal_code} #{address} #{name}"
  end

  def self.status_search(sortword)
    case sortword
    when 0
      where(order_status: 0)
    when 1
      where(order_status: 1)
    when 2
      where(order_status: 2)
    when 3
      where(order_status: 3)
    when 4
      where(order_status: 4)
    end
  end

  belongs_to :customer
  has_many :order_products, class_name: "OrderProduct", foreign_key: "order_id", dependent: :destroy

  scope :scope_six_days_ago, ->   {where(created_at: Time.current.ago(6.days).all_day)}
  scope :scope_five_days_ago, ->  {where(created_at: Time.current.ago(5.days).all_day)}
  scope :scope_four_days_ago, ->  {where(created_at: Time.current.ago(4.days).all_day)}
  scope :scope_three_days_ago, -> {where(created_at: Time.current.ago(3.days).all_day)}
  scope :scope_two_days_ago, ->   {where(created_at: Time.current.ago(2.days).all_day)}
  scope :scope_a_day_ago, ->      {where(created_at: Time.current.ago(1.days).all_day)}
  scope :scope_today, ->          {where(created_at: Time.current.beginning_of_day..Time.current)}
end

app/models/order_product.rb
class OrderProduct < ApplicationRecord
  belongs_to :product
  belongs_to :order_info, foreign_key: "order_id"

  validates :price, :quantity, presence: true
end

app/models/product.rb
class Product < ApplicationRecord
  attachment :image

  validates :name, :introduction, :genre_id, :price, :image, presence: true
  has_many :cart_products, dependent: :destroy
  belongs_to :genre
  has_many :order_products, dependent: :destroy
  has_many :comments, dependent: :destroy

  TAX_RATE = 1.1

  def tax_price
    (self.price*TAX_RATE).floor
  end

  def status
    self.sales_status == true ? "販売中" : "販売停止中"
  end

end

app/controllers/admin/base.rb
class Admin::Base < ApplicationController
  before_action :authenticate_admin!, except: [:top, :about]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  class Forbidden < ActionController::ActionControllerError; end
  class IPAddressRejected < ActionController::ActionControllerError; end
  
  include ErrorHandlers if Rails.env.production?

  def after_sign_in_path_for(resource)
    case resource
    when Admin
      admin_order_infos_path
    when Customer
      public_customers_path
    end
  end
  
  def after_sign_out_path_for(resource)
    case resource
    when :admin
      new_admin_session_path
    when :customer
      public_root_path
    end
    
  end

  protected
  def configure_permitted_parameters
    if resource_class == Customer
      devise_parameter_sanitizer.permit(:sign_up, keys: [:family_name, :given_name, :family_name_kana, :given_name_kana, :email, :postal_code, :address, :phone])
      devise_parameter_sanitizer.permit(:sign_in,keys:[:email])
    end
  end

end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController
  def not_found
    render status: 404
  end

  def unprocessable_entity
    render status: 422
  end

  def internal_server_error
    render status: 500
  end
end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/order_infos_helper.rb
module Admin::OrderInfosHelper
  def order_status_hash
    order_hash = { '0': "入金待ち", '1': "入金確認", '2':"製作中", '3':"発送準備中", '4':"発送済み" }
    return order_hash
  end

  def sales_status_hash
    sales_hash = { '0': "着手不可", '1': "製作待ち", '2':"製作中", '3':"制作完了" }
    return sales_hash
  end

  def payment_method_hash
    payment_hash = { '0': "クレジットカード", '1': "銀行振込" }
    return payment_hash
  end
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/errors_helper.rb
module ErrorsHelper
end

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/layouts/_error.html.erb
<div class="error-message text-danger">
<% if model.errors.any? %>
  <p><%= model.errors.count %> つのエラーがあります。</p>
  <% model.errors.full_messages.each do |message| %>
    <p>・<%= message %></p>
  <% end %>
<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Naganocake</title>
    <%= csrf_meta_tags %>
    <script src="https://kit.fontawesome.com/cdc0e6c98c.js" crossorigin="anonymous"></script>
    
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css"/>
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick-theme.css"/>
    <script type="text/javascript" src="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>
  </head>

  <body>
    <div id="wrapper">
      <%= render "shared/header" %>
      
      <div class="container px-5 px-sm-0">
        <%= render "shared/flash_message" %>
        <div class="main">
          <%= yield %>
        </div>
      </div>
      
      <%= render "shared/footer" %>
    </div>
  </body>
</html>

app/views/shared/_flash_message.html.erb
<% flash.each do |message_type, message| %>
  <% if message_type == "notice" %>
    <% message_type = "success" %>
  <% elsif message_type == "alert" %>
    <% message_type = "danger" %>
  <% end %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer-main">
    <div class="container py-5">
      <div class="row">
        <div class="col-6 col-md">
          <h5>NAGANO CAKE</h5>
          <ul class="list-unstyled text-small">
            <li><%= link_to "Top", public_root_path, class:"text-muted" %></li>
            <li><%= link_to "About", public_about_path, class:"text-muted" %></li>
          </ul>
        </div>
        <div class="col-6 col-md">
          <h5>Products</h5>
          <ul class="list-unstyled text-small">
            <li><%= link_to "商品一覧", public_products_path, class:"text-muted" %></li>

            <% Genre.all.each do |g| %>
              <li><%= link_to g.name, public_search_path(value: g.id, how: "match"), class:"text-muted" %></li>
            <% end %>
          </ul>
        </div>
        <div class="col-6 col-md">
          <h5>Access</h5>
          <ul class="list-unstyled text-small text-muted">
          〒100-8111</br>
          東京都千代田区千代田１−１
          </ul>
        </div>
        <div class="col-12 col-md">
          <small><%= link_to "To Administrator", new_admin_session_path, class:"d-block mb-3 text-muted" %></small>
          <small class="d-block mb-3 text-muted">&copy; 2021</small>
        </div>
      </div>
  </div>
</footer>

app/views/shared/_header.html.erb
<header>
  <nav class="navbar navbar-expand-md navbar-dark header-main">
    <div class="container">
      <h1 class="m-0">
          <%= link_to "NAGANO CAKE", public_root_path, class:"navbar-brand d-block" %>
      </h1>
      <div id="grobalNav" class="collapse navbar-collapse">
        <ul class="navbar-nav ml-auto">
           <% if customer_signed_in? %>
           <!--User is alreadey log in-->
              <div class="nav-item welcome-text p-2 pr-4 pl-4 rounded-pill d-flex align-items-center">
                ようこそ<%= Customer.find(current_customer.id).family_name %>さん！
              </div>
              <li class="nav-item pl-4 active">
                <%= link_to "MyPage", public_customers_path, class:"nav-link text-center" %>
              </li>
              <li class="nav-item pl-4">
                <%= link_to "PRODUCTS", public_products_path, class:"nav-link text-center" %>
              </li>
              <li class="nav-item pl-4">
                <%= link_to "CART", public_cart_products_path, class:"nav-link text-center" %>
              </li>
              <li class="nav-item pl-4">
                <%= link_to "LOGOUT", destroy_customer_session_path, class:"nav-link text-center", method: :delete %>
              </li>
              <li class="nav-item pl-4">
                <%= form_with url:public_search_path, method: :get, local:true do |f| %>
                  <%= f.search_field :value, placeholder: 'キーワードを入力', class:'border-0' %>
                    <%=  f.hidden_field :how, value:'partical' %>
                    <%= f.button type: "submit", class:'btn btn-light ml-2' do %>
                      <i class="fas fa-search"></i>
                    <% end %>
                <% end %>
              </li>
           <% elsif admin_signed_in? %>
           <!--admin is alreadey log in-->
              <li class="nav-item pl-4 active">
                <%= link_to "PRODUCTS", admin_products_path, class:"nav-link text-center" %>
              </li>
              <li class="nav-item pl-4 active">
                <%= link_to "CUSTOMERS", admin_customers_path, class:"nav-link text-center" %>
              </li>
              <li class="nav-item pl-4">
                <%= link_to "ORDER", admin_order_infos_path, class:"nav-link text-center" %>
              </li>
              <li class="nav-item pl-4">
                <%= link_to "GENRE", admin_genres_path, class:"nav-link text-center" %>
              </li>
              <li class="nav-item pl-4">
                <%= link_to "LOGOUT", destroy_admin_session_path, class:"nav-link text-center", method: :delete %>
              </li>
           <% else %>
           <!--User is log out-->
              <li class="nav-item pl-4 active">
                <%= link_to "ABOUT", public_about_path, class:"nav-link text-center" %>
              </li>
              <li class="nav-item pl-4">
                <%= link_to "PRODUCTS", public_products_path, class:"nav-link text-center" %>
              </li>
              <li class="nav-item pl-4">
                <%= link_to "SIGN UP", new_customer_registration_path, class:"nav-link text-center" %>
              </li>
              <li class="nav-item pl-4">
                <%= link_to "LOGIN", new_customer_session_path, class:"nav-link text-center" %>
              </li>
              <li class="nav-item pl-4">
                <%= form_with url:public_search_path, method: :get, local:true do |f| %>
                  <%= f.search_field :value, placeholder: 'キーワードを入力', class:'border-0' %>
                    <%=  f.hidden_field :how, value:'partical' %>
                    <%= f.button type: "submit", class:'btn btn-light ml-2' do %>
                      <i class="fas fa-search"></i>
                    <% end %>
                <% end %>
              </li>
            <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>